services:
  nginx:
    build: ./nginx
    container_name: nginx-server
    ports:
      - "80:80"
    depends_on:
      - blog-api
    volumes:
      - ./logs/nginx:/var/log/nginx
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  blog-api:
    build: ./blog-api
    container_name: blog-api
    environment:
      - PORT=5000
    volumes:
      - ./logs/blog-api:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

volumes:
  logs:

networks:
  default:
    name: nginx-simple